services:
  postgres:
    image: postgres:16
    container_name: tienda-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - ./init-databases/authenticationservice/create.sql:/docker-entrypoint-initdb.d/1-create.sql
      - ./init-databases/authenticationservice/insert.sql:/docker-entrypoint-initdb.d/2-insert.sql
    #volumes:
    #  - ./init-databases:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 5s